name: HoYoLAB Daily Check-in

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Run check-in script
        run: bun checkin
        env:
          HOYO_TOKENS: ${{ secrets.HOYO_TOKENS }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
